name: flutter_mgt_utils
description: "FlutterMgtUtils"
version: 0.0.1

environment:
  flutter: ">=3.29.0"
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  provider: ^6.1.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.3
  json_serializable: ^6.9.4
  lint: ^2.8.0
